# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Xbeta_cpp <- function(X, beta) {
    .Call(`_lame_Xbeta_cpp`, X, beta)
}

outer_cpp <- function(a, b) {
    .Call(`_lame_outer_cpp`, a, b)
}

gof_stats_cpp <- function(Y) {
    .Call(`_lame_gof_stats_cpp`, Y)
}

#' Sample dynamic additive effects with AR(1) evolution
#'
#' @param a_current Current 2D array of row effects (n x T)
#' @param b_current Current 2D array of column effects (n x T)
#' @param Z_array 3D array of latent positions (n x n x T)
#' @param EZ_array 3D array of expected values without additive effects (n x n x T)
#' @param rho_ab AR(1) parameter for additive effects
#' @param sigma_ab Innovation standard deviation
#' @param Sab Covariance matrix for a and b (2x2)
#' @param symmetric Whether the network is symmetric
#' @return List with updated a and b arrays
sample_dynamic_ab_cpp <- function(a_current, b_current, Z_array, EZ_array, rho_ab, sigma_ab, Sab, symmetric) {
    .Call(`_lame_sample_dynamic_ab_cpp`, a_current, b_current, Z_array, EZ_array, rho_ab, sigma_ab, Sab, symmetric)
}

#' Sample AR(1) parameter for dynamic additive effects
#'
#' @param a_mat Matrix of row effects (n x T)
#' @param b_mat Matrix of column effects (n x T)
#' @param sigma_ab Innovation standard deviation
#' @param rho_current Current value of rho
#' @param symmetric Whether the network is symmetric
#' @param prior_mean Prior mean for rho. Used only when \code{prior_sd > 0}.
#' @param prior_sd Prior SD for rho. \code{prior_sd < 0} (the default)
#'   selects a Jeffreys-like flat prior; a positive value switches to a
#'   truncated Normal(prior_mean, prior_sd^2) prior.
#' @return Updated rho value
sample_rho_ab_cpp <- function(a_mat, b_mat, sigma_ab, rho_current, symmetric, prior_mean = 0.0, prior_sd = -1.0) {
    .Call(`_lame_sample_rho_ab_cpp`, a_mat, b_mat, sigma_ab, rho_current, symmetric, prior_mean, prior_sd)
}

#' Sample innovation variance for dynamic additive effects
#'
#' @param a_mat Matrix of row effects (n x T)
#' @param b_mat Matrix of column effects (n x T)
#' @param rho_ab AR(1) parameter
#' @param symmetric Whether the network is symmetric
#' @param prior_shape Shape parameter for inverse gamma prior
#' @param prior_scale Scale parameter for inverse gamma prior
#' @return Updated sigma_ab value
sample_sigma_ab_cpp <- function(a_mat, b_mat, rho_ab, symmetric, prior_shape = 2.0, prior_scale = 1.0) {
    .Call(`_lame_sample_sigma_ab_cpp`, a_mat, b_mat, rho_ab, symmetric, prior_shape, prior_scale)
}

#' Initialize dynamic additive effects with AR(1) structure
#'
#' @param n Number of actors
#' @param T Number of time points
#' @param rho_ab AR(1) parameter
#' @param sigma_ab Innovation standard deviation
#' @param mean_a Mean for row effects
#' @param mean_b Mean for column effects
#' @return List with initialized a and b matrices
init_dynamic_ab_cpp <- function(n, T, rho_ab, sigma_ab, mean_a = 0.0, mean_b = 0.0) {
    .Call(`_lame_init_dynamic_ab_cpp`, n, T, rho_ab, sigma_ab, mean_a, mean_b)
}

#' Sample the dynamic-block beta path via FFBS
#'
#' Forward-filter / backward-sample the AR(1) state-space model for the
#' dynamic-block beta coefficients. Returns the joint draw of beta_dyn at
#' every time period.
#'
#' @param Xdyn_list T-length list of (n*n) x p_dyn long-format design
#'   matrices for the dynamic block (column-major reshape per period).
#' @param Xstat_list T-length list of (n*n) x p_static long-format design
#'   matrices for the static block.
#' @param Z_list T-length list of (n x n) latent matrices.
#' @param offset_list T-length list of (n x n) offset matrices (a_i + b_j +
#'   U_i'V_j contributions; everything that's not in X*beta).
#' @param beta_static Length p_static current static beta vector.
#' @param rho_by_coef Length p_dyn vector of AR(1) rho values for each
#'   dynamic coefficient. (Per-block but expanded per-column for vectorised
#'   indexing.)
#' @param sigma_by_coef Length p_dyn vector of AR(1) innovation standard
#'   deviations for each dynamic coefficient.
#' @param Lambda Block-diagonal innovation scale matrix (p_dyn x p_dyn).
#'   Combined with sigma^2 to give Q = sigma^2 * Lambda.
#' @param beta0_mean Length p_dyn prior mean for beta at t=0.
#' @param beta0_cov  p_dyn x p_dyn prior covariance for beta at t=0.
#' @param s2 Dyadic variance.
#' @param dyad_rho Dyadic correlation (ignored when use_dyad_rho=FALSE).
#' @param bipartite Whether the network is bipartite.
#' @param symmetric Whether the network is symmetric.
#' @param use_dyad_rho Whether to use the dyad-corr branch (TRUE only for
#'   unipartite, asymmetric, with a non-zero rho).
#' @return List with: path -- a (T x p_dyn) matrix of beta draws (one row
#'   per period); chol_fail -- integer count of Cholesky failures.
sample_beta_dynamic_cpp <- function(Xdyn_list, Xstat_list, Z_list, offset_list, beta_static, rho_by_coef, sigma_by_coef, Lambda, beta0_mean, beta0_cov, s2, dyad_rho, bipartite, symmetric, use_dyad_rho) {
    .Call(`_lame_sample_beta_dynamic_cpp`, Xdyn_list, Xstat_list, Z_list, offset_list, beta_static, rho_by_coef, sigma_by_coef, Lambda, beta0_mean, beta0_cov, s2, dyad_rho, bipartite, symmetric, use_dyad_rho)
}

#' Sample the static-block beta conditional on the dynamic path
#'
#' Conjugate Gaussian update for the static coefficient block, treating the
#' dynamic path as known. Uses a flat-ish ridge-style prior `prior_prec` on
#' the static beta (typically diag(1/g) to match the existing g-prior path).
#'
#' @param Xdyn_list T-length list of long-format dynamic design matrices.
#' @param Xstat_list T-length list of long-format static design matrices.
#' @param Z_list T-length list of latent (n x n) matrices.
#' @param offset_list T-length list of (n x n) offsets.
#' @param beta_dyn_path (T x p_dyn) dynamic path matrix.
#' @param prior_mean Length p_static prior mean.
#' @param prior_prec p_static x p_static prior precision.
#' @param s2 Dyadic variance.
#' @param dyad_rho Dyadic correlation.
#' @param bipartite TRUE/FALSE.
#' @param symmetric TRUE/FALSE.
#' @param use_dyad_rho TRUE/FALSE.
#' @return List with: beta -- length p_static; chol_fail -- integer.
sample_beta_static_cpp <- function(Xdyn_list, Xstat_list, Z_list, offset_list, beta_dyn_path, prior_mean, prior_prec, s2, dyad_rho, bipartite, symmetric, use_dyad_rho) {
    .Call(`_lame_sample_beta_static_cpp`, Xdyn_list, Xstat_list, Z_list, offset_list, beta_dyn_path, prior_mean, prior_prec, s2, dyad_rho, bipartite, symmetric, use_dyad_rho)
}

#' Sample the AR(1) rho for each dynamic block
#'
#' Truncated-Normal full conditional, one rho per block.
#'
#' @param beta_path (T x p_dyn) matrix of beta draws.
#' @param group_id Length p_dyn integer vector (1-based) of block IDs.
#' @param n_groups Number of distinct block IDs.
#' @param Lambda_inv (p_dyn x p_dyn) inverse of the (full) Lambda scale.
#' @param sigma_by_coef Length p_dyn vector of per-coef sigma (block-shared).
#' @param rho_current Length n_groups vector of current rho values.
#' @param rho_prior_mean Length n_groups vector of prior means.
#' @param rho_prior_sd   Length n_groups vector of prior SDs.
#' @param rho_lower Lower truncation bound (typically 0).
#' @param rho_upper Upper truncation bound (typically 0.999).
#' @return Length n_groups vector of new rho values.
sample_rho_beta_cpp <- function(beta_path, group_id, n_groups, Lambda_inv, sigma_by_coef, rho_current, rho_prior_mean, rho_prior_sd, rho_lower = 0.0, rho_upper = 0.999) {
    .Call(`_lame_sample_rho_beta_cpp`, beta_path, group_id, n_groups, Lambda_inv, sigma_by_coef, rho_current, rho_prior_mean, rho_prior_sd, rho_lower, rho_upper)
}

#' Sample the AR(1) innovation sigma for each dynamic block
#'
#' Inverse-Gamma full conditional, one sigma per block.
#'
#' @param beta_path (T x p_dyn) matrix.
#' @param group_id Length p_dyn integer vector (1-based) of block IDs.
#' @param n_groups Number of distinct block IDs.
#' @param Lambda_inv (p_dyn x p_dyn) inverse of the (full) Lambda scale.
#' @param rho_by_group Length n_groups vector of current rho values.
#' @param prior_shape Length n_groups vector of IG shape parameters.
#' @param prior_scale Length n_groups vector of IG scale parameters.
#' @return Length n_groups vector of new sigma values.
sample_sigma_beta_cpp <- function(beta_path, group_id, n_groups, Lambda_inv, rho_by_group, prior_shape, prior_scale) {
    .Call(`_lame_sample_sigma_beta_cpp`, beta_path, group_id, n_groups, Lambda_inv, rho_by_group, prior_shape, prior_scale)
}

#' Compute EZ when beta is time-varying
#'
#' Rebuild the (n x n x T) or (nA x nB x T) EZ cube using a per-period beta
#' vector. Mirrors get_EZ_cpp / get_EZ_bip_cpp but accepts a (T x p) beta
#' matrix where each row is the beta for that period.
#'
#' @param Xlist T-length list of design arrays (each n x n x p or nA x nB x p).
#' @param beta_full_path (T x p) matrix of per-period beta. For coefficients
#'   that are NOT in the dynamic block, the rows are identical (the static
#'   beta replicated across all periods).
#' @param a_mat (n_a x T) row effects (or repmat-ed static effects).
#' @param b_mat (n_b x T) column effects.
#' @param U_cube (n_u x R x T) row latent positions (or replicated-static).
#' @param V_cube (n_v x R x T) column latent positions.
#' @param G (R x R or RA x RB) interaction matrix (bipartite); identity for
#'   unipartite.
#' @param bipartite TRUE/FALSE.
#' @param symmetric TRUE/FALSE.
#' @return n_a x n_b x T cube of EZ values.
get_EZ_dynamic_beta_cpp <- function(Xlist, beta_full_path, a_mat, b_mat, U_cube, V_cube, G, bipartite, symmetric) {
    .Call(`_lame_get_EZ_dynamic_beta_cpp`, Xlist, beta_full_path, a_mat, b_mat, U_cube, V_cube, G, bipartite, symmetric)
}

#' Update dynamic latent positions using AR(1) process
#'
#' @param U_current Current 3D array of U positions (n x R x T)
#' @param V_current Current 3D array of V positions (n x R x T)
#' @param ET 3D array of residuals (n x n x T)
#' @param rho_uv AR(1) autoregressive parameter for latent positions
#' @param sigma_uv Innovation standard deviation for latent positions
#' @param s2 Dyadic variance
#' @param shrink Whether to apply shrinkage
#' @param symmetric Whether network is symmetric
#' @return List with updated U and V arrays
rUV_dynamic_fc_cpp <- function(U_current, V_current, ET, rho_uv, sigma_uv, s2, shrink, symmetric) {
    .Call(`_lame_rUV_dynamic_fc_cpp`, U_current, V_current, ET, rho_uv, sigma_uv, s2, shrink, symmetric)
}

#' Initialize dynamic latent positions with AR(1) structure
#'
#' @param n Number of actors
#' @param R Latent dimension
#' @param T Number of time points
#' @param rho_uv AR(1) parameter
#' @param sigma_uv Innovation standard deviation
#' @return 3D array of latent positions (n x R x T)
init_dynamic_positions <- function(n, R, T, rho_uv, sigma_uv) {
    .Call(`_lame_init_dynamic_positions`, n, R, T, rho_uv, sigma_uv)
}

#' Sample AR(1) parameter for dynamic latent factors
#'
#' Uses a conjugate Normal(prior_mean, prior_sd^2) prior on rho. Defaults
#' (prior_mean = 0, prior_sd = 1) preserve the historical N(0,1) behaviour
#' for backward compatibility; lame::lame() passes the user-set
#' prior$rho_uv_mean / prior$rho_uv_sd explicitly.
#'
#' @param U_cube 3D array of U positions (n x R x T)
#' @param V_cube 3D array of V positions (n x R x T)
#' @param sigma_uv Innovation standard deviation
#' @param rho_current Current value of rho (ignored; full conditional)
#' @param symmetric Whether network is symmetric
#' @param prior_mean Prior mean for rho (default 0)
#' @param prior_sd Prior SD for rho (default 1)
#' @return Updated rho value
sample_rho_uv <- function(U_cube, V_cube, sigma_uv, rho_current, symmetric, prior_mean = 0.0, prior_sd = 1.0) {
    .Call(`_lame_sample_rho_uv`, U_cube, V_cube, sigma_uv, rho_current, symmetric, prior_mean, prior_sd)
}

#' Sample innovation variance for dynamic latent factors
#'
#' @param U_cube 3D array of U positions (n x R x T)
#' @param V_cube 3D array of V positions (n x R x T)
#' @param rho_uv AR(1) parameter
#' @param symmetric Whether network is symmetric
#' @return Updated sigma_uv value
sample_sigma_uv <- function(U_cube, V_cube, rho_uv, symmetric) {
    .Call(`_lame_sample_sigma_uv`, U_cube, V_cube, rho_uv, symmetric)
}

#' Update dynamic latent positions with snap-shift model selection
#'
#' Like rUV_dynamic_fc_cpp but, for t > 0, chooses per actor between an AR(1)
#' drift prior and a diffuse N(0, kappa^2 I) snap prior via a Gaussian
#' log-marginal-likelihood model selection, drawing a Bernoulli snap indicator
#' delta and sampling the latent position from the selected posterior.
#'
#' @param U_current Current 3D array of U positions (n x R x T)
#' @param V_current Current 3D array of V positions (n x R x T)
#' @param ET 3D array of residuals (n x n x T)
#' @param rho_uv AR(1) autoregressive parameter for the drift prior
#' @param sigma_uv Innovation standard deviation for the drift prior
#' @param s2 Dyadic variance
#' @param kappa Diffuse snap-prior standard deviation (kappa^2 >> sigma_uv^2)
#' @param pi_snap Prior snap probability
#' @param delta_u_current Current sender-side snap indicators from the previous sweep
#' @param delta_v_current Current receiver-side snap indicators from the previous sweep
#' @param shrink Whether to apply shrinkage
#' @param symmetric Whether network is symmetric
#' @return List with updated U, V arrays and delta_u, delta_v snap indicators
rUV_dynamic_snap_fc_cpp <- function(U_current, V_current, ET, rho_uv, sigma_uv, s2, kappa, pi_snap, delta_u_current, delta_v_current, shrink, symmetric) {
    .Call(`_lame_rUV_dynamic_snap_fc_cpp`, U_current, V_current, ET, rho_uv, sigma_uv, s2, kappa, pi_snap, delta_u_current, delta_v_current, shrink, symmetric)
}

#' Update dynamic latent positions with heavy-tailed (Student-t) AR(1) innovations
#'
#' Like rUV_dynamic_fc_cpp but each AR(1) innovation is Student-t rather than
#' Gaussian, via a scale-mixture: the innovation for u_{t,i} has variance
#' sigma^2 / lambda_{t,i} with lambda_{t,i} ~ Gamma(nu/2, nu/2). Provides a
#' continuous heavy-tailed alternative to the discrete snap-shift model.
#'
#' @param U_current Current 3D array of U positions (n x R x T)
#' @param V_current Current 3D array of V positions (n x R x T)
#' @param ET 3D array of residuals (n x n x T)
#' @param rho_uv AR(1) autoregressive parameter
#' @param sigma_uv Innovation scale
#' @param s2 Dyadic variance
#' @param nu Student-t degrees of freedom
#' @param lambda_u Current local scales for U (n x T)
#' @param lambda_v Current local scales for V (n x T)
#' @param shrink Whether to apply shrinkage
#' @param symmetric Whether network is symmetric
#' @return List with updated U, V arrays and lambda_u, lambda_v local scales
rUV_dynamic_t_fc_cpp <- function(U_current, V_current, ET, rho_uv, sigma_uv, s2, nu, lambda_u, lambda_v, shrink, symmetric) {
    .Call(`_lame_rUV_dynamic_t_fc_cpp`, U_current, V_current, ET, rho_uv, sigma_uv, s2, nu, lambda_u, lambda_v, shrink, symmetric)
}

#' Bipartite dynamic UV Gibbs update
#'
#' Replaces the nested R loops for bipartite dynamic_uv in lame.R.
#' Uses direct 2x2 inverse formula for common R=2 case.
#'
#' @param U_cube 3D array (nA x RA x T)
#' @param V_cube 3D array (nB x RB x T)
#' @param E 3D array of residuals (nA x nB x T)
#' @param G Interaction matrix (RA x RB)
#' @param rho_uv AR(1) persistence parameter
#' @param sigma_uv Innovation standard deviation
#' @param s2 Dyadic variance
#' @return List with updated U_cube, V_cube
rUV_dynamic_bip_fc_cpp <- function(U_cube, V_cube, E, G, rho_uv, sigma_uv, s2) {
    .Call(`_lame_rUV_dynamic_bip_fc_cpp`, U_cube, V_cube, E, G, rho_uv, sigma_uv, s2)
}

count_four_cycles_bip_cpp <- function(Y) {
    .Call(`_lame_count_four_cycles_bip_cpp`, Y)
}

compute_degrees_bip_cpp <- function(Y) {
    .Call(`_lame_compute_degrees_bip_cpp`, Y)
}

clustering_coef_bip_cpp <- function(Y) {
    .Call(`_lame_clustering_coef_bip_cpp`, Y)
}

get_EZ_bip_cpp <- function(base, a, b, U, V, G) {
    .Call(`_lame_get_EZ_bip_cpp`, base, a, b, U, V, G)
}

outer_ab_bip_cpp <- function(a, b) {
    .Call(`_lame_outer_ab_bip_cpp`, a, b)
}

get_EZ_cpp <- function(Xlist, beta, ab, U, V) {
    .Call(`_lame_get_EZ_cpp`, Xlist, beta, ab, U, V)
}

ldZgbme_cpp <- function(Z, Y, EZ, rho, s2) {
    .Call(`_lame_ldZgbme_cpp`, Z, Y, EZ, rho, s2)
}

rZ_pois_fc_cpp <- function(Z, EZ, rho, s2, Y) {
    .Call(`_lame_rZ_pois_fc_cpp`, Z, EZ, rho, s2, Y)
}

ldZgbme_nrm_cpp <- function(Z, Y, EZ, rho, s2) {
    .Call(`_lame_ldZgbme_nrm_cpp`, Z, Y, EZ, rho, s2)
}

ldZgbme_pois_exposure_cpp <- function(Z, Y, EZ, rho, s2, log_exposure) {
    .Call(`_lame_ldZgbme_pois_exposure_cpp`, Z, Y, EZ, rho, s2, log_exposure)
}

rZ_pois_fc_exposure_cpp <- function(Z, EZ, rho, s2, Y, log_exposure) {
    .Call(`_lame_rZ_pois_fc_exposure_cpp`, Z, EZ, rho, s2, Y, log_exposure)
}

simY_pois_exposure <- function(EZ, exposure) {
    .Call(`_lame_simY_pois_exposure`, EZ, exposure)
}

simY_pois <- function(EZ) {
    .Call(`_lame_simY_pois`, EZ)
}

rwish_cpp <- function(S0, nu) {
    .Call(`_lame_rwish_cpp`, S0, nu)
}

rUV_rep_fc_cpp <- function(ET, U, V, rho, s2, iSe2, maxmargin, shrink, rLoopIDs) {
    .Call(`_lame_rUV_rep_fc_cpp`, ET, U, V, rho, s2, iSe2, maxmargin, shrink, rLoopIDs)
}

rUV_sym_fc_cpp <- function(E, U, V, s2, shrink, uLoopIDs) {
    .Call(`_lame_rUV_sym_fc_cpp`, E, U, V, s2, shrink, uLoopIDs)
}

#' Batch normal Z sampling across all time periods
#'
#' Replaces the per-time-period R loop with a single C++ call that loops
#' internally, reducing R-to-C++ transition overhead.
#'
#' @param Z 3D array of latent values (n x n x T)
#' @param EZ 3D array of expected values (n x n x T)
#' @param rho Dyadic correlation parameter
#' @param s2 Dyadic variance
#' @param Y 3D array of observed values (n x n x T)
#' @return List with updated Z and E_nrm (residuals)
rZ_nrm_batch_cpp <- function(Z, EZ, rho, s2, Y) {
    .Call(`_lame_rZ_nrm_batch_cpp`, Z, EZ, rho, s2, Y)
}

#' Batch binary Z sampling across all time periods (bipartite, rho=0)
#'
#' Vectorized probit update for bipartite binary networks without dyadic correlation.
#'
#' @param Z 3D array of latent values (nA x nB x T)
#' @param EZ 3D array of expected values (nA x nB x T)
#' @param Y 3D array of observed values (nA x nB x T)
#' @return Updated Z array
rZ_bin_bip_batch_cpp <- function(Z, EZ, Y) {
    .Call(`_lame_rZ_bin_bip_batch_cpp`, Z, EZ, Y)
}

#' Batch tobit Z sampling across all time periods (bipartite, rho=0)
#'
#' @param Z 3D array of latent values (nA x nB x T)
#' @param EZ 3D array of expected values (nA x nB x T)
#' @param s2 Dyadic variance
#' @param Y 3D array of observed values (nA x nB x T)
#' @return Updated Z array
rZ_tob_bip_batch_cpp <- function(Z, EZ, s2, Y) {
    .Call(`_lame_rZ_tob_bip_batch_cpp`, Z, EZ, s2, Y)
}

rZ_bin_fc_cpp <- function(ZT, EZT, rho, YT) {
    .Call(`_lame_rZ_bin_fc_cpp`, ZT, EZT, rho, YT)
}

rZ_bin_fc_single <- function(Z, EZ, rho, Y) {
    .Call(`_lame_rZ_bin_fc_single`, Z, EZ, rho, Y)
}

rZ_bin_fc_exact <- function(Z, EZ, rho, Y) {
    .Call(`_lame_rZ_bin_fc_exact`, Z, EZ, rho, Y)
}

rZ_bin_fc_fixed <- function(Z, EZ, rho, Y) {
    .Call(`_lame_rZ_bin_fc_fixed`, Z, EZ, rho, Y)
}

#' Compute X'X and X'y for bipartite covariate regression
#'
#' Replaces the O(T x p^2 x n^2) nested R loop for bipartite XtX and Xty
#' computation with a single C++ call.
#'
#' @param Xlist List of T arrays, each nA x nB x p
#' @param resid 3D array of residuals nA x nB x T
#' @param p Number of covariates
#' @return List with XtX (p x p) and Xty (p vector)
compute_XtX_Xty_bip_cpp <- function(Xlist, resid, p) {
    .Call(`_lame_compute_XtX_Xty_bip_cpp`, Xlist, resid, p)
}

#' Compute Xbeta product for bipartite networks
#'
#' Computes sum_k beta_k * X_k for a single time slice
#'
#' @param X 3D array (nA x nB x p) of covariates for one time period
#' @param beta Coefficient vector of length p
#' @return nA x nB matrix
Xbeta_bip_cpp <- function(X, beta) {
    .Call(`_lame_Xbeta_bip_cpp`, X, beta)
}

#' Full bipartite Gibbs update for beta, a, b
#'
#' Single C++ function replacing the bipartite beta/a/b update block in lame.R
#'
#' @param Z 3D array (nA x nB x T)
#' @param Xlist List of T arrays (nA x nB x p)
#' @param UV_eff nA x nB matrix (U*G*V' or U*V')
#' @param a_current Current row effects (length nA)
#' @param b_current Current column effects (length nB)
#' @param s2 Dyadic variance
#' @param g_prior G-prior parameter
#' @param va Row effect variance (diagonal element of Sab)
#' @param vb Column effect variance (diagonal element of Sab)
#' @param rvar Whether to update row effects
#' @param cvar Whether to update column effects
#' @return List with beta, a, b
rbeta_ab_bip_gibbs_cpp <- function(Z, Xlist, UV_eff, a_current, b_current, s2, g_prior, va, vb, rvar, cvar) {
    .Call(`_lame_rbeta_ab_bip_gibbs_cpp`, Z, Xlist, UV_eff, a_current, b_current, s2, g_prior, va, vb, rvar, cvar)
}

rbeta_ab_rep_fc_cpp <- function(ZT, Xr, Xc, mX, mXt, XX, XXt, iSe2, Sabs, k, G, g = 100.0) {
    .Call(`_lame_rbeta_ab_rep_fc_cpp`, ZT, Xr, Xc, mX, mXt, XX, XXt, iSe2, Sabs, k, G, g)
}

test_rbeta_inputs <- function(ZT, Xr, Xc, mX, mXt, XX, XXt, iSe2, Sabs, k, G, g = 100.0) {
    invisible(.Call(`_lame_test_rbeta_inputs`, ZT, Xr, Xc, mX, mXt, XX, XXt, iSe2, Sabs, k, G, g))
}

rrho_mh_rep_cpp <- function(ET, rho, s2) {
    .Call(`_lame_rrho_mh_rep_cpp`, ET, rho, s2)
}

rs2_rep_fc_cpp <- function(ET, rhoMat) {
    .Call(`_lame_rs2_rep_fc_cpp`, ET, rhoMat)
}

sample_U_bip_cpp <- function(R, V, G, lambdaU, s2) {
    .Call(`_lame_sample_U_bip_cpp`, R, V, G, lambdaU, s2)
}

sample_V_bip_cpp <- function(R, U, G, lambdaV, s2) {
    .Call(`_lame_sample_V_bip_cpp`, R, U, G, lambdaV, s2)
}

sample_G_bip_cpp <- function(R, U, V, lambdaG, s2) {
    .Call(`_lame_sample_G_bip_cpp`, R, U, V, lambdaG, s2)
}

canon_orient_bip_cpp <- function(U, V, G) {
    .Call(`_lame_canon_orient_bip_cpp`, U, V, G)
}

